//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.29 at 06:34:36 PM CET 
//


package org.dsaw.javacup.tactics.jvc2013.mansporting.tray;

public class TrayectoriaPunto {

  protected double desplazamientoH;
  protected double desplazamientoV;
  protected double velocidadH;
  protected double velocidadV;
  protected int iteraciones;
  protected double probabilidadControl;
  protected Trayectoria trayectoria;

  /**
   * Gets the value of the desplazamientoH property.
   */
  public double getDesplazamientoH() {
    return desplazamientoH;
  }

  /**
   * Sets the value of the desplazamientoH property.
   */
  public void setDesplazamientoH(double value) {
    this.desplazamientoH = value;
  }

  /**
   * Gets the value of the desplazamientoV property.
   */
  public double getDesplazamientoV() {
    return desplazamientoV;
  }

  /**
   * Sets the value of the desplazamientoV property.
   */
  public void setDesplazamientoV(double value) {
    this.desplazamientoV = value;
  }

  /**
   * Gets the value of the probabilidadControl property.
   */
  public double getProbabilidadControl() {
    return probabilidadControl;
  }

  /**
   * Sets the value of the probabilidadControl property.
   */
  public void setProbabilidadControl(double value) {
    this.probabilidadControl = value;
  }

  /**
   * Gets the value of the iteraciones property.
   */
  public int getIteraciones() {
    return iteraciones;
  }

  /**
   * Sets the value of the iteraciones property.
   */
  public void setIteraciones(int value) {
    this.iteraciones = value;
  }

  /**
   * Gets the value of the trayectoria property.
   *
   * @return possible object is {@link Object }
   */
  public Trayectoria getTrayectoria() {
    return trayectoria;
  }

  /**
   * Sets the value of the trayectoria property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setTrayectoria(Trayectoria value) {
    this.trayectoria = value;
  }

  public double getVelocidadH() {
    return velocidadH;
  }

  public void setVelocidadH(double velocidadH) {
    this.velocidadH = velocidadH;
  }

  public double getVelocidadV() {
    return velocidadV;
  }

  public void setVelocidadV(double velocidadV) {
    this.velocidadV = velocidadV;
  }


}
